# Clippy configuration file
# See: https://rust-lang.github.io/rust-clippy/master/index.html

# Lint level settings
msrv = "1.70.0"  # Minimum supported Rust version
avoid-breaking-exported-api = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true

# Complexity thresholds
cognitive-complexity-threshold = 30
excessive-nesting-threshold = 5
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
type-complexity-threshold = 250
single-char-binding-names-threshold = 4

# Documentation
missing-docs-in-crate-items = true
# doc-valid-idents = ["PostgreSQL", "GitHub", "GitLab", "IPv4", "IPv6", "ClojureScript", "CoffeeScript", "JavaScript", "PureScript", "TypeScript", "WebAssembly", "NaN", "NaNs", "OAuth", "GraphQL", "OCaml", "OpenGL", "OpenMP", "OpenSSH", "OpenSSL", "OpenStreetMap", "OpenDNS", "WebGL", "TensorFlow", "TrueType", "iOS", "macOS", "FreeBSD", "TeX", "LaTeX", "BibTeX", "BibLaTeX", "MinGW", "CamelCase"]

# Style preferences
enum-variant-name-threshold = 3
struct-field-name-threshold = 3
max-struct-bools = 3
max-fn-params-bools = 3
max-include-file-size = 1000000
literal-representation-threshold = 16
trivial-copy-size-limit = 8

# Paths and names
enforced-import-renames = [
    { path = "std::io::Write", rename = "IoWrite" },
    { path = "std::fmt::Write", rename = "FmtWrite" },
]
allowed-scripts = ["Latin"]
allowed-duplicate-crates = []

# Allow certain patterns
allowed-wildcard-imports = [
    "futures::prelude::*",
    "tokio::prelude::*",
]

# Disallowed names
disallowed-names = ["foo", "bar", "baz", "quux", "tmp", "temp", "test"]

# Specific lint configurations
vec-box-size-threshold = 4096
array-size-threshold = 512
enum-variant-size-threshold = 200
future-size-threshold = 64

# Performance related
large-error-threshold = 128

# Standard library lint settings
standard-macro-braces = [
    { name = "assert", brace = "(" },
    { name = "assert_eq", brace = "(" },
    { name = "assert_ne", brace = "(" },
    { name = "debug_assert", brace = "(" },
    { name = "debug_assert_eq", brace = "(" },
    { name = "debug_assert_ne", brace = "(" },
    { name = "format", brace = "(" },
    { name = "format_args", brace = "(" },
    { name = "print", brace = "(" },
    { name = "println", brace = "(" },
    { name = "eprint", brace = "(" },
    { name = "eprintln", brace = "(" },
    { name = "todo", brace = "(" },
    { name = "unimplemented", brace = "(" },
    { name = "unreachable", brace = "(" },
    { name = "panic", brace = "(" },
    { name = "vec", brace = "[" },
]

# Third party configuration
cargo-ignore-publish = false

# Pattern matching
matches-for-let-else = "AllTypes"
unreadable-literal-lint-fractions = true

# Async specific
# future-size-threshold is already set above

# Documentation URLs
# doc-comment-code-block-check-backticks = true

# Path configurations
absolute-paths-allowed-crates = []
absolute-paths-max-segments = 2

# Misc
suppress-restriction-lint-in-const = false
enable-raw-pointer-heuristic-for-send = true