# cargo-audit configuration file

[advisories]
# Vulnerabilities to ignore
ignore = [
    "RUSTSEC-2023-0071",  # RSA vulnerability in sqlx-mysql (not used, only SQLite backend is used)
    "RUSTSEC-2024-0436",  # paste crate unmaintained (used by rmcp dependency)
]

# Warnings to allow
informational_warnings = ["unmaintained"]