project:
  name: vide-ticket
  description: A high-performance ticket management system
  default_assignee: null
  default_priority: medium
ui:
  theme: auto
  emoji: true
  page_size: 20
  date_format: '%Y-%m-%d %H:%M'
git:
  enabled: true
  branch_prefix: ticket/
  auto_branch: true
  commit_template: null
plugins:
  enabled: []
  directory: .vide-ticket/plugins
