project:
  name: vibe-ticket
  description: null
  default_assignee: null
  default_priority: medium
ui:
  theme: auto
  emoji: true
  page_size: 20
  date_format: '%Y-%m-%d %H:%M'
git:
  enabled: true
  branch_prefix: ticket/
  auto_branch: true
  commit_template: null
  worktree_enabled: true
  worktree_prefix: ../{project}-ticket-
  worktree_cleanup_on_close: false
plugins:
  enabled: []
  directory: .vibe-ticket/plugins
